#!/bin/bash
# @file ~/.bash_prompt
# @brief sets my custom bash prompt to execute the Python prompt
# @author Oscar Bezi (oscar@bezi.io)
# @since 5 June 2014
#===============================================================================

# it's a prompt command to make it execute properly every time
if [ -f ~/.python_prompt/prompt.py ]; then
    PROMPT_COMMAND='PS1="$(python2.7 ~/.python_prompt/prompt.py $? $COLUMNS)"';
else
    PROMPT_COMMAND='PS1=">"';
fi
